version: "3.9"

services:
  exporter:
    container_name: exporter
    command: --statsd.mapping-config=/tmp/statsd_mapping.yml
    image: prom/statsd-exporter
    volumes:
      - ./statsd-mapping.yaml:/tmp/statsd_mapping.yml
    ports:
      # - 9102:9102
      - 9125:9125
      - 9125:9125/udp
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider --proxy=off localhost:9102/-/healthy || exit 1"
        ]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 5s
    depends_on:
      prometheus:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # ports:
    #   - 9090:9090
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider --proxy=off localhost:9090/-/healthy || exit 1"
        ]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 5s

  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.19
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/automatic.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${ALLOW_SIGN_UP}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider --proxy=off localhost:3000/api/health || exit 1"
        ]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 5s
    depends_on:
      prometheus:
        condition: service_healthy

volumes:
  grafana-data:
    external: true
