# Guide: https://dev.to/kirklewis/metrics-with-prometheus-statsd-exporter-and-grafana-5145

global:
  scrape_interval:      15s
  evaluation_interval:  15s

scrape_configs:
  # optional: this makes the metrics available to us about Promethus itself.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # tells Prometheus to scrape metrics an address over port 9123
  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['exporter:9102'] # see statsd-exporter further down